export const SUBSTANTIVE_TOPIC_FACTS: Record<string, string> = {
  "chem-1-1": "Solid particles are closely packed and vibrate about fixed positions; heating increases their energy and can change state.",
  "chem-1-2": "Diffusion is the net movement of particles from higher concentration to lower concentration due to random motion.",
  "chem-2-1": "An element has one type of atom; a compound has chemically bonded elements; a mixture contains substances not chemically bonded.",
  "chem-2-2": "Atoms have a nucleus of protons and neutrons with electrons arranged around it; electron arrangement helps explain periodic behaviour.",
  "chem-2-3": "Isotopes have the same proton number but different neutron numbers; relative atomic mass is a weighted isotope average.",
  "chem-4-2": "A hydrogen-oxygen fuel cell converts chemical energy into electrical energy and produces water overall.",
  "chem-6-1": "A physical change does not form a new substance; a chemical change forms one or more new substances.",
  "chem-7-2": "Metal oxides are generally basic, while many non-metal oxides are acidic.",
  "chem-8-1": "The Periodic Table is ordered by proton number and shows recurring property patterns; group members have related outer-electron arrangements.",
  "chem-8-2": "Group I reactivity increases down the group because the outer electron is farther from the nucleus and easier to remove.",
  "chem-8-3": "Group VII halogen reactivity decreases down the group; a more reactive halogen can displace a less reactive halide.",
  "chem-8-4": "Transition elements commonly form coloured compounds, variable oxidation states and can act as catalysts.",
  "chem-8-5": "Noble gases have complete outer electron shells and are very unreactive in ordinary conditions.",
  "chem-9-1": "Metals generally conduct heat and electricity well and can be malleable because of metallic bonding.",
  "chem-9-2": "Metal uses depend on properties such as strength, density, conductivity, corrosion resistance and melting point.",
  "chem-9-3": "An alloy is a mixture containing a metal and other element(s), used to modify properties such as strength or hardness.",
  "chem-9-5": "Rusting of iron requires oxygen and water; coatings and sacrificial protection can reduce corrosion.",
  "chem-10-1": "Water treatment removes impurities and microorganisms; filtration removes insoluble particles and disinfection reduces microbes.",
  "chem-10-2": "The Haber process makes ammonia from nitrogen and hydrogen in a reversible reaction under suitable industrial conditions.",
  "chem-10-3a": "Air is mainly nitrogen and oxygen; pollutants include carbon monoxide, sulfur dioxide, nitrogen oxides and particulates.",
  "chem-10-3b": "Greenhouse gases absorb outgoing infrared radiation and contribute to the greenhouse effect and climate change.",
  "chem-11-2": "Systematic organic naming identifies a parent chain and the positions of relevant functional groups or substituents.",
  "chem-11-3": "Petroleum is separated by fractional distillation into fractions with different boiling ranges and uses.",
  "chem-11-4": "Alkanes are saturated hydrocarbons containing only single carbon-carbon bonds.",
  "chem-12-2": "Acid-base titration measures reacting volumes to an endpoint; concordant titres improve reliability.",
  "chem-12-4": "Separation methods are selected using physical properties such as boiling point, solubility and movement between phases.",
  "math-e1-1": "Prime numbers have exactly two positive factors; rational numbers can be written as a fraction of integers.",
  "math-e1-2": "In a Venn diagram, intersection means common to sets and union means in at least one set.",
  "math-e1-3": "A square root is a value that squares to the original number; powers represent repeated multiplication.",
  "math-e1-4": "Fractions, decimals and percentages can represent the same value when converted correctly.",
  "math-e1-5": "Numbers should be compared using a consistent representation and place-value understanding when ordered.",
  "math-e1-6": "Brackets take precedence, then multiplication/division, then addition/subtraction in standard order of operations.",
  "math-e1-7": "For a non-zero base, a^m × a^n = a^(m+n) and a^m ÷ a^n = a^(m−n).",
  "math-e1-8": "Standard form writes a number as A × 10^n where 1 ≤ A < 10.",
  "math-e1-9": "Rounding uses a stated place value or significant figures; estimation checks whether an answer is sensible.",
  "math-e1-12": "A rate compares a change in one quantity with a unit of another, such as km per hour.",
  "math-e1-14": "Calculator use still requires correct mode, brackets, order of operations and a reasonableness check.",
  "math-e1-15": "Time calculations require careful conversion between hours, minutes and seconds.",
  "math-e1-16": "Money questions can involve percentages, exchange rates, decimal arithmetic and appropriate currency rounding.",
  "math-e1-17": "Exponential growth or decay uses repeated multiplication by a constant multiplier.",
  "math-e2-1": "Algebraic expressions use letters to represent values; substitution replaces variables with their given values.",
  "math-e2-4": "Index laws include (a^m)^n = a^(mn) and a^(−n) = 1/a^n for non-zero a.",
  "math-e2-6": "An inequality uses <, >, ≤ or ≥; multiplying or dividing by a negative reverses the sign.",
  "math-e2-8": "Direct proportion has y = kx, while inverse proportion has y = k/x for non-zero k.",
  "math-e2-9": "Practical graphs model how measurable quantities change and need suitable scales, labels and units.",
  "math-e2-11": "A curve sketch should show relevant features such as intercepts, turning points, asymptotes and overall shape.",
  "math-e3-1": "A coordinate is (x, y), with x giving horizontal position and y vertical position.",
  "math-e3-2": "A straight-line graph can be plotted from key points or a table using a sensible scale and labels.",
  "math-e3-4": "The midpoint is the average of corresponding coordinates; distance uses coordinate differences in a Pythagorean calculation.",
  "math-e3-5": "In y = mx + c, m is the gradient and c is the y-intercept.",
  "math-e3-6": "Parallel straight lines have the same gradient.",
  "math-e3-7": "For non-vertical lines, perpendicular gradients have product −1; one is the negative reciprocal of the other.",
  "math-e4-1": "Geometric terms precisely describe relationships such as parallel, perpendicular, adjacent and vertically opposite.",
  "math-e4-2": "Constructions use accurate ruler-and-compass methods for loci, perpendicular bisectors and angle bisectors.",
  "math-e4-3": "A scale drawing represents real lengths using one fixed scale factor consistently.",
  "math-e4-5": "Reflectional symmetry uses mirror lines; rotational symmetry means a shape matches itself after certain turns.",
  "math-e5-1": "Length, area and volume use different units; area and volume conversions use squared or cubed scale factors.",
  "math-e5-2": "Area measures a region while perimeter measures the distance around its boundary.",
  "math-e5-5": "Compound shapes can be split into simpler shapes, or an unwanted part can be subtracted from a larger one.",
  "math-e6-3": "Exact trigonometric values include sin 30° = 1/2, cos 60° = 1/2 and tan 45° = 1.",
  "math-e6-4": "Sine and cosine graphs are periodic and have predictable ranges, intercepts and key values.",
  "math-e6-6": "3D trigonometry can often be reduced to right triangles and solved with Pythagoras or trigonometric ratios in stages.",
  "math-e7-2": "A two-dimensional vector can be represented by horizontal and vertical components and added component-by-component.",
  "math-e7-3": "The magnitude of vector (x, y) is √(x² + y²).",
  "math-e8-1": "Probability ranges from 0 to 1; for equally likely outcomes it is favourable outcomes divided by total outcomes.",
  "math-e8-2": "Relative frequency is observed proportion; expected frequency is probability multiplied by total trials.",
  "math-e9-1": "Statistical data may be discrete or continuous and categorical or numerical; classification affects suitable methods.",
  "math-e9-2": "Statistical interpretation compares values, spread, trends and context rather than one number alone.",
  "math-e9-4": "Bar charts, pie charts and box plots are selected according to data type and the comparison required.",
  "math-e9-5": "A scatter diagram shows paired data and can indicate correlation; correlation alone does not prove causation.",
  "pak-kq2": "Mughal decline involved succession problems, internal divisions, regional challenges and the expanding East India Company.",
  "pak-kq5": "Urdu and regional languages have contributed to education, literature, identity and cultural expression in Pakistan.",
  "pak-kq13": "East Pakistan became Bangladesh in 1971 after long political and regional tensions followed by conflict and Indian intervention.",
  "pak-kq14": "Bhutto's period included nationalisation and the 1973 Constitution, while Zia's rule included martial law and Islamisation measures.",
  "pak-kq15": "The 1990s saw alternating civilian governments alongside continuing political and economic instability.",
  "pak-kq16": "Pakistan's foreign relations have been shaped by security, regional disputes, alliances, trade and relations with major powers.",
  "pak-p2-7": "Transport and telecommunications connect people, goods and information and support trade, services and economic development.",
  "isl-quran-1": "Sura 2:255 emphasises Allah's sovereignty, knowledge, power and authority over creation.",
  "isl-quran-2": "Sura 6:101-103 stresses Allah as creator without partner or offspring and beyond ordinary human sight while seeing all things.",
  "isl-quran-3": "Sura 41:37 directs believers not to worship the sun or moon but to worship their Creator.",
  "isl-quran-4": "Sura 42:4-5 describes Allah as owner of the heavens and earth and the angels glorifying Him and seeking forgiveness.",
  "isl-quran-5": "Sura 112 teaches Allah's oneness, self-sufficiency and uniqueness, with no offspring or equal.",
  "isl-quran-6": "Sura 1 praises Allah, highlights mercy and judgement, and asks for guidance to the straight path.",
  "isl-quran-7": "Sura 2:21-22 calls people to worship their Creator and points to creation and provision as signs of His power.",
  "isl-quran-8": "Sura 96:1-5 links reading, the pen, creation and knowledge with Allah's teaching and generosity.",
  "isl-quran-9": "Sura 99 presents the final earthquake and accountability for deeds, including very small deeds.",
  "isl-quran-10": "Sura 114 teaches believers to seek refuge in Allah from the whisperer who promotes evil thoughts.",
  "isl-quran-11": "Sura 2:30-37 presents Adam's creation, knowledge, Iblis's refusal, the Garden test and Adam's repentance.",
  "isl-quran-12": "Sura 6:75-79 presents Abraham rejecting the worship of created heavenly bodies and turning to the Creator.",
  "isl-quran-13": "Sura 5:110 recounts blessings and miracles given to Jesus by Allah's permission, including teaching and healing.",
  "isl-quran-14": "Sura 93 reassures the Prophet and commands kindness to orphans and beggars while remembering Allah's blessings.",
  "isl-quran-15": "Sura 108 refers to abundant blessing and directs prayer and sacrifice to Allah.",
  "isl-hadith-1": "Hadith 1 teaches sincerity to Allah, His Book, His Messenger, Muslim leaders and ordinary people.",
  "isl-hadith-2": "Hadith 2 teaches wanting for one's brother what one wants for oneself.",
  "isl-hadith-3": "Hadith 3 links belief in Allah and the Last Day with good speech, generosity to neighbours and hospitality.",
  "isl-hadith-4": "Hadith 4 emphasises obligatory prayers and fasting, following what is lawful and avoiding what is forbidden.",
  "isl-hadith-5": "Hadith 5 counts justice, helping others, good words, walking to prayer and removing harm as forms of charity.",
  "isl-hadith-6": "Hadith 6 gives levels for opposing wrong according to ability: action, then speech, then the heart.",
  "isl-hadith-7": "Hadith 7 praises the believer who strives in Allah's way with person and property.",
  "isl-hadith-8": "Hadith 8 includes several forms of death or struggle associated with martyrdom, not only battlefield death.",
  "isl-hadith-9": "Hadith 9 praises food earned through the work of one's own hands.",
  "isl-hadith-10": "Hadith 10 gives great merit to caring for widows and poor people.",
  "isl-hadith-11": "Hadith 11 promises special closeness in paradise for one who cares for an orphan.",
  "isl-hadith-12": "Hadith 12 instructs leaders to be gentle, avoid needless hardship and not alienate people.",
  "isl-hadith-13": "Hadith 13 compares neglected Qur'an study to released tethered camels and teaches regular revision.",
  "isl-hadith-14": "Hadith 14 asks for mercy for a person who is kind when buying, selling and demanding money back.",
  "isl-hadith-15": "Hadith 15 links showing mercy to others with receiving Allah's mercy.",
  "isl-hadith-16": "Hadith 16 compares believers to a single body so that suffering in one part affects the whole.",
  "isl-hadith-17": "Hadith 17 teaches that modesty produces good.",
  "isl-hadith-18": "Hadith 18 contrasts genuine faith with pride and warns of the spiritual danger of arrogance.",
  "isl-hadith-19": "Hadith 19 contrasts temporary worldly life with the believer's hope of the Hereafter.",
  "isl-hadith-20": "Hadith 20 teaches that Allah looks at hearts and deeds rather than forms and possessions.",
  "isl-p1-3a": "The Prophet's early life included orphanhood, trustworthiness, marriage to Khadija and the first revelation in the Cave of Hira in 610.",
  "isl-p1-3b": "During the Makkan period the Prophet preached tawhid and faced ridicule, persecution and a boycott of his supporters.",
  "isl-p1-4b": "The first Islamic community included the Muhajirun, Ansar, close companions and scribes who supported the community and preserved teachings.",
  "isl-p2-2a": "Hadith scholarship developed methods for preserving and evaluating reports, including attention to isnad, matn and reliability classifications."
};
